analyzer:

  exclude:
    - "**/*.g.dart"
    - "**/*.gen.dart"
    - "**/*.mock.dart"
    - "**/*.freezed.dart"
    - "*/firebase_options.dart"



include: package:very_good_analysis/analysis_options.yaml


linter:

  rules:
    lines_longer_than_80_chars: false
    always_use_package_imports: false
    omit_local_variable_types: false
    prefer_single_quotes: false
    require_trailing_commas: false
    prefer_relative_imports: true