name: flutter_weather_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:


  cached_network_image: ^3.2.3
  cloud_firestore: ^4.5.3
  crypto: ^3.0.2
  cupertino_icons: ^1.0.2
  dio: ^5.1.1
  equatable: ^2.0.5
  firebase_analytics: ^10.2.1
  firebase_auth: ^4.2.2
  firebase_core: ^2.10.0
  firebase_crashlytics: ^3.1.2
  firebase_messaging: ^14.4.1
  firebase_storage: ^11.1.1
  flex_color_scheme: ^7.0.5
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  flutter_svg: ^2.0.5
  gap: ^3.0.0
  go_router: ^7.0.0
  google_fonts: ^4.0.4
  google_sign_in: ^6.1.0
  hooks_riverpod: ^2.3.6
  iconsax: ^0.0.8
  image_cropper: ^3.0.3
  image_picker: ^0.8.7+4
  intl: ^0.18.1
  lottie: ^2.3.2
  share_plus: ^4.5.3
  shimmer: ^2.0.0
  sign_in_with_apple: ^4.3.0
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  #
  flutter_lints: ^2.0.0
  #
  flutter_test:
    sdk: flutter
  #
  mockito: ^5.4.0
  #
  very_good_analysis: ^4.0.0+1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
